CREATE TABLE spring_data(
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '学生id',
  `name` VARCHAR(20) NOT NULL COMMENT '学生姓名',
  `age` INT NOT NULL COMMENT '年龄',
  PRIMARY KEY (id)
)ENGINE =InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET =utf8 COMMENT ='SpringData';

INSERT INTO spring_data(name,age)
VALUES ('ZHANGSAN',20),('LISI',21),('WANGWU',22);